version: "3.9"
services:
  nginx:
   image: nginx:alpine
   container_name: nginx
   ports:
   - "8080:80"
   volumes:
   - ./src:/var/www/html
   - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
   depends_on:
     - php
     - mysql



  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
    - /mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
    - ./src:/var/www/html
    ports:
    - "9000:9000"



